version: "0.1"
services:
  gpu:
    image: nvidia/cuda:11.0.3-runtime-ubuntu20.04
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  pathml:
    image: chunvong/pathml-cv-test:latest
    ports:
      - "8888:8888"
